#!/bin/python

import sys

n,k = raw_input().strip().split(' ')
n,k = [int(n),int(k)]
s = raw_input().strip()
friends = map(int,raw_input().strip().split(' '))
for i in friends:
    if s[i-1]=='0':
        print 'YES'
        break
    else:
        continue
else:
        print "NO"
    
